---
- hosts: localhost
  vars:
    ansible_connection: local

  tasks:

    - name: Creates directory for plasma
      file:
        path: /media/fakeinstallroot/
        state: directory

    - name: bootstrap arm using qemu
      shell:  qemu-debootstrap --arch arm64 --components=main --include=apt,bash,dpkg,gnupg2 --variant=minbase unstable /media/fakeinstallroot http://deb.debian.org/debian/
      args:
        creates: /media/fakeinstallroot/usr/bin/

    - name: Creates directory
      file:
        path: /media/fakeinstallroot/build/
        state: directory

    - name: Creates directory
      file:
        path: /build/download
        state: directory


    - name: KDE Plasma - Part 1 - Blue Devil BlueTooth
      get_url:
        url: https://download.kde.org/stable/plasma/5.20.3/bluedevil-5.20.3.tar.xz
        dest: /build/download/bluedevil.tar.xz
    
    
    - name: KDE Plasma - Part 1 - Breeze 
      get_url:
        url:  https://download.kde.org/stable/plasma/5.20.3/breeze-5.20.3.tar.xz
        dest: /build/download/breeze.tar.xz
        
    - name: KDE Plasma - Part 1 - Breeze GRUB
      get_url:
        url:  https://download.kde.org/stable/plasma/5.20.3/breeze-grub-5.20.3.tar.xz
        dest: /build/download/breeze.tar.xz
        
        
    - name: KDE Plasma - Part 1 - Breeze GTK
      get_url:
        url:  https://download.kde.org/stable/plasma/5.20.3/breeze-gtk-5.20.3.tar.xz
        dest: /build/download/breeze-gtk.tar.xz
        
    - name: KDE Plasma - Part 1 - Breeze Plymouth
      get_url:
        url:  https://download.kde.org/stable/plasma/5.20.3/breeze-plymouth-5.20.3.tar.xz
        dest: /build/download/breeze-plymouth.tar.xz
        
    - name: KDE Plasma - Part 1 - Discover
      get_url:
        url:  https://download.kde.org/stable/plasma/5.20.3/discover-5.20.3.tar.xz
        dest: /build/download/breeze-discover.tar.xz
        
    - name: KDE Plasma - Part 1 - KActivity
      get_url:
        url: https://download.kde.org/stable/plasma/5.20.3/kactivitymanagerd-5.20.3.tar.xz
        dest: /build/download/kactivitymanager.tar.xz
        
    - name: KDE Plasma - Part 1 - Dr Konqi
      get_url:
        url: https://download.kde.org/stable/plasma/5.20.3/drkonqi-5.20.3.tar.xz
        dest: /build/download/drkonqi.tar.xz 
        
    - name: KDE Plasma - Part 1 - KDE Cli Tools
      get_url:
        url: https://download.kde.org/stable/plasma/5.20.3/kde-gtk-config-5.20.3.tar.xz
        dest: /build/download/kde-gtk-config.tar.xz 
   
    - name: KDE Plasma - Part 1 -kde-cli-tools
      get_url:
        url: https://download.kde.org/stable/plasma/5.20.3/kde-cli-tools-5.20.3.tar.xz
        dest: /build/download/kde-cli-tools.tar.xz 
 
   - name: KDE Plasma - Part 1 -kdecoration
      get_url:
        url: https://download.kde.org/stable/plasma/5.20.3/kdecoration-5.20.3.tar.xz
        dest: /build/download/kdecoration.tar.xz 

   - name: KDE Plasma - Part 1 - kdeplasma-addons
      get_url:
        url: https://download.kde.org/stable/plasma/5.20.3/kdeplasma-addons-5.20.3.tar.xz
        dest: /build/download/kdeplasma-addons.tar.xz 
        
   - name: KDE Plasma - Part 1 - kgamma5
      get_url:
        url:  https://download.kde.org/stable/plasma/5.20.3/kgamma5-5.20.3.tar.xz
        dest: /build/download/kgamma5.tar.xz 
        
   - name: KDE Plasma - Part 1 - khotkeys
      get_url:
        url:  https://download.kde.org/stable/plasma/5.20.3/khotkeys-5.20.3.tar.xz
        dest: /build/download/khotkeys.tar.xz 
        
   - name: KDE Plasma - Part 1 -kinfocenter-
      get_url:
        url: https://download.kde.org/stable/plasma/5.20.3/kinfocenter-5.20.3.tar.xz
        dest: /build/download/kinfocenter.tar.xz 
	
	- name: KDE Plasma - Part 1 -kmenuedit-
	  get_url:
	    url: https://download.kde.org/stable/plasma/5.20.3/kmenuedit-5.20.3.tar.xz
	    dest: /build/download/kmenuedit.tar.xz          
	    
	- name: KDE Plasma - Part 1 -kscreen-
	  get_url:
	    url: https://download.kde.org/stable/plasma/5.20.3/kscreen-5.20.3.tar.xz
	    dest: /build/download/kscreen.tar.xz                 
             
   	- name: KDE Plasma - Part 1 -kscreenlocker
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/kscreenlocker-5.20.3.tar.xz
	    dest: /build/download/kscreenlocker.tar.xz        
	    
   	- name: KDE Plasma - Part 1 -ksshaskpass-
	  get_url:
	    url:  https://download.kde.org/stable/plasma/5.20.3/ksshaskpass-5.20.3.tar.xz
	    dest: /build/download/ksshaskpass.tar.xz   
    
   	- name: KDE Plasma - Part 1 -kscreenlocker
	  get_url:
	    url: https://download.kde.org/stable/plasma/5.20.3/kwallet-pam-5.20.3.tar.xz
	    dest: /build/download/kwallet-pam.tar.xz   
	    
	    
   	- name: KDE Plasma - Part 1 -kscreenlocker
	  get_url:
	    url:  https://download.kde.org/stable/plasma/5.20.3/kwayland-integration-5.20.3.tar.xz
	    dest: /build/download/kwayland-integration.tar.xz   
	    
   	- name: KDE Plasma - Part 1 -kwayland-server
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/kwayland-server-5.20.3.tar.xz
	    dest: /build/download/kwayland-server.tar.xz   

   	- name: KDE Plasma - Part 1 -kwin
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/kwin-5.20.3.tar.xz
	    dest: /build/download/kwin.tar.xz   
 
  	- name: KDE Plasma - Part 1 -kwrite
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/kwrited-5.20.3.tar.xz
	    dest: /build/download/kwrite.tar.xz  
   
   
   	- name: KDE Plasma - Part 1 - libkscreen
	  get_url:
	    url:  https://download.kde.org/stable/plasma/5.20.3/libkscreen-5.20.3.tar.xz
	    dest: /build/download/libkscreen.tar.xz  
	    
	- name: KDE Plasma - Part 1 -libksysguard-
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/libksysguard-5.20.3.tar.xz
	    dest: /build/download/libksysguard.tar.xz  

	- name: KDE Plasma - Part 1 -milou
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/milou-5.20.3.tar.xz
	    dest: /build/download/milou.tar.xz  
   
    - name: KDE Plasma - Part 1 -oxygen
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/oxygen-5.20.3.tar.xz
	    dest: /build/download/oxygen.tar.xz  

    - name: KDE Plasma - Part 1 - plasma-browser-integration
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/plasma-browser-integration-5.20.3.tar.xz
	    dest: /build/download/plasma-browser-integration.tar.xz  

    - name: KDE Plasma - Part 1 -plasma-desktop
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/plasma-desktop-5.20.3.tar.xz
	    dest: /build/download/plasma-desktop.tar.xz  

    - name: KDE Plasma - Part 1 - plasma-disks	
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/plasma-disks-5.20.3.tar.xz
	    dest: /build/download/plasma-disks.tar.xz  

    - name: KDE Plasma - Part 1 -plasma-integration	
	  get_url:
	    url:  https://download.kde.org/stable/plasma/5.20.3/plasma-integration-5.20.3.tar.xz
	    dest: /build/download/plasma-integration.tar.xz  

    - name: KDE Plasma - Part 1 - plasma-nano
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/plasma-nano-5.20.3.tar.xz
	    dest: /build/download/plasma-nano.tar.xz  

    - name: KDE Plasma - Part 1 -plasma-nm
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/plasma-nm-5.20.3.tar.xz
	    dest: /build/download/plasma-nm.tar.xz  


    - name: KDE Plasma - Part 1 -plasma-pa
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/plasma-pa-5.20.3.tar.xz
	    dest: /build/download/plasma-pa.tar.xz  


    - name: KDE Plasma - Part 1 - plasma-phone-components
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/plasma-phone-components-5.20.3.tar.xz
	    dest: /build/download/plasma-phone-components.tar.xz  


    - name: KDE Plasma - Part 1 -plasma-sdk
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/plasma-sdk-5.20.3.tar.xz
	    dest: /build/download/plasma-sdk.tar.xz  


    - name: KDE Plasma - Part 1 plasma-thunderbolt
	  get_url:
	    url:  https://download.kde.org/stable/plasma/5.20.3/plasma-thunderbolt-5.20.3.tar.xz
	    dest: /build/download/plasma-thunderbolt.tar.xz  


    - name: KDE Plasma - Part 1 -plasma-vault
	  get_url:
	    url:  https://download.kde.org/stable/plasma/5.20.3/plasma-vault-5.20.3.tar.xz
	    dest: /build/download/plasma-vault.tar.xz  


    - name: KDE Plasma - Part 1 -plasma-workspac
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/plasma-workspace-5.20.3.tar.xz
	    dest: /build/download/plasma-workspace.tar.xz  


    - name: KDE Plasma - Part 1 -plasma-workspace-wallpapers
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/plasma-workspace-wallpapers-5.20.3.tar.xz
	    dest: /build/download/plasma-workspace-wallpapers.tar.xz  

    - name: KDE Plasma - Part 1 - 	plymouth-kcm
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/plymouth-kcm-5.20.3.tar.xz
	    dest: /build/download/plymouth-kcm.tar.xz  
	    
    - name: KDE Plasma - Part 1 -polkit-kde-agent-
	  get_url:
	    url:   https://download.kde.org/stable/plasma/5.20.3/polkit-kde-agent-1-5.20.3.tar.xz
	    dest: /build/download/plasma-nm.tar.xz  
	    
    - name: KDE Plasma - Part 1 -powerdevil
	  get_url:
	    url:  https://download.kde.org/stable/plasma/5.20.3/powerdevil-5.20.3.tar.xz
	    dest: /build/download/powerdevil.tar.xz  
   
    - name: KDE Plasma - Part 1 -sddm-kcm
	  get_url:
	    url:  https://download.kde.org/stable/plasma/5.20.3/sddm-kcm-5.20.3.tar.xz
	    dest: /build/download/sddm-kcm.tar.xz  
	    
    - name: KDE Plasma - Part 1 -systemsettings
	  get_url:
	    url:  https://download.kde.org/stable/plasma/5.20.3/systemsettings-5.20.3.tar.xz
	    dest: /build/download/systemsettings.tar.xz      
	    
	 - name: KDE Plasma - Part 1 - xdg-desktop-portal-kde
	  get_url:
	    url:  https://download.kde.org/stable/plasma/5.20.3/xdg-desktop-portal-kde-5.20.3.tar.xz
	    dest: /build/download/xdg-desktop-portal-kde.tar.xz    
    
    - name: Prepare SDDM and Plasma BUILD
      command: /build/scripts/createKdePlasmaDependBuild.sh

    - name: BUILD KDE 1
      command: /build/scripts/kdebuildscript.sh
      args:
        creates: /build/kdebuildscriptdone.txt
    - name: BUILD KDE 2
      command: /build/scripts/kdebuildscript2.sh
      args:
        creates: /build/kdebuildscriptdone2.txt
    - name: BUILD KDE 3
      command: /build/scripts/kdebuildscript3.sh
      args:
        creates: /build/kdebuildscriptdone3.txt
    - name: BUILD KDE 4
      command: /build/scripts/kdebuildscript4.sh
      args:
        creates: /build/kdebuildscriptdone4.txt
    - name: BUILD KDE 5
      command: /build/scripts/kdebuildscript5.sh
      args:
        creates: /build/kdebuildscriptdone5.txt
    - name: BUILD KDE 6
      command: /build/scripts/kdebuildscript6.sh
      args:
        creates: /build/kdebuildscriptdone6.txt
    - name: BUILD KDE 7
      command: /build/scripts/kdebuildscript7.sh
      args:
        creates: /build/kdebuildscriptdone7.txt

    - name: pine64 crust uboot git clone
      git:
        repo: 'https://gitlab.com/pine64-org/crust-meta.git'
        dest: '/build/crust-meta'
        force: yes
        version: master
    - name: Download linux firmware
      git:
        repo: 'https://megous.com/git/linux-firmware'
        dest: '/build/firmware'
        force: yes
        version: master


    - name: Change pinebook to pinephone
      replace:
        path: "/build/crust-meta/Makefile"
        regexp: 'pinebook'
        replace: 'pinephone'

    - name: get megi kernel
      get_url:
        url: https://gitlab.com/pine64-org/linux/-/archive/megi-kernel-5.8/linux-megi-kernel-5.8.tar.gz
        dest: /build

    - name: Extract kernel
      unarchive:
        src: /build/linux-megi-kernel-5.8.tar.gz
        dest: /build

    - name:  build default kernel config for pinephone
      make:
        chdir: /build/linux-megi-kernel-5.8
        params:
          ARCH: arm64
          CROSS_COMPILE: aarch64-linux-gnu-
        target: pinephone_defconfig

    - name: patch the config
      replace:
        path: /build/linux-megi-kernel-5.8/.config
        regexp: CONFIG_EXTRA_FIRMWARE_DIR="\/workspace\/megous\.com\/orangepi-pc\/firmware"
        replace: CONFIG_EXTRA_FIRMWARE_DIR="/build/firmware"

    - name: patch the config
      replace:
        path:  /build/linux-megi-kernel-5.8/.config
        regexp: CONFIG_EXTRA_FIRMWARE_DIR="\/lib\/firmware"
        replace: CONFIG_EXTRA_FIRMWARE_DIR="/build/firmware"

    - name: patch the config
      replace:
        path: /build/linux-megi-kernel-5.8/.config
        regexp: CONFIG_EXTRA_FIRMWARE=".*"
        replace: CONFIG_EXTRA_FIRMWARE="anx7688-fw.bin brcm/brcmfmac43362-sdio.bin brcm/brcmfmac43456-sdio.bin hm5065-af.bin rtl_bt/rtl8723bs_config-pine64.bin  rtl_bt/rtl8723cs_xx_config-pinebook.bin  rtl_bt/rtl8723cs_xx_config-pinephone.bin  rtl_bt/rtl8723cs_xx_fw.bin hm5065-init.bin  regulatory.db  rtlwifi/rtl8188eufw.bin"

    - name: Build the kernel
      make:
        chdir: /build/linux-megi-kernel-5.8
        params:
          ARCH: arm64
          CROSS_COMPILE: aarch64-linux-gnu-
        target: all

    - name: Build the uboot and crust
      make:
        chdir: /build/crust-meta

    - name: Create a disk image
      command: dd if=/dev/zero of=/build/scripts/mobian.img bs=1024M count=13 conv=sync

    - name: Create loopback
      command: mknod -m 0660 "/build/recovery-pinephone-loop0" b 7 101

    - name: Attach loopback
      command: losetup -P /build/recovery-pinephone-loop0 /build/scripts/mobian.img

    - name: Create a new primary partition with a size of 1GiB
      parted:
        device: /build/recovery-pinephone-loop0
        label: msdos
        number: 1
        flags: [ boot ]
        part_type: primary
        state: present
        part_end: 1GiB

    - name: Create a new primary partition with a size of 6GiB
      parted:
        device: /build/recovery-pinephone-loop0
        label: msdos
        number: 2
        part_type: primary
        state: present
        part_start: 1GiB
        part_end: 12.9GiB

    - pause:
        seconds: 5

    - name: Make loopback nodes
      shell: /build/scripts/createnode.sh

    - name: Create a ext2 filesystem on loopback part 1
      filesystem:
        fstype: ext2
        dev: /build/recovery-pinephone-loop0p1

    - name: label e2boot
      command: e2label /build/recovery-pinephone-loop0p1 BOOT

    - name: Create a f2fs filesystem on loopback part 2
      filesystem:
       fstype: f2fs
       dev: /build/recovery-pinephone-loop0p2

    - name: Creates directory
      file:
        path: /media/root/
        state: directory

    - name: Mount up device by label
      mount:
        path: /media/root/
        src: /build/recovery-pinephone-loop0p2
        fstype: f2fs
        state: mounted

    - name: Creates directory
      file:
        path: /media/root/boot
        state: directory

    - name: Mount up device by label
      mount:
        path: /media/root/boot
        src: /build/recovery-pinephone-loop0p1
        fstype: ext2
        state: mounted


    - name: bootstrap arm using qemu
      shell:  qemu-debootstrap --arch arm64 --components=main --include=apt,bash,dpkg,gnupg2 --variant=minbase unstable /media/root  http://deb.debian.org/debian/
      args:
        creates: /media/root/usr/bin/

    - name: install necessary debian packages for pinephone
      command: /build/scripts/createImageSecond.sh

    - name: Synchronization /usr for KDE install to /debian install
      synchronize:
        src: /media/fakeinstallroot/usr/
        dest: /media/root/usr

    - name: install the modules
      make:
        chdir: /build/linux-megi-kernel-5.8
        params:
          ARCH: arm64
          CROSS_COMPILE: aarch64-linux-gnu-
          INSTALL_MOD_PATH: /media/root/
        target:  modules_install

    - name: install the dtbs
      make:
        chdir: /build/linux-megi-kernel-5.8
        params:
          ARCH: arm64
          INSTALL_DTBS_PATH: /media/root/boot
          CROSS_COMPILE: aarch64-linux-gnu-
        target:  dtbs_install

    - name: Make System Map
      shell: /sbin/depmod -b "/media/root/" -F System.map $(make kernelversion|tr '\n' ' ')
      args:
        chdir: /build/linux-megi-kernel-5.8

    - name: Copy file with owner and permissions
      copy:
        src: /build/linux-megi-kernel-5.8/System.map
        dest: /media/root/boot/System.map
        owner: root
        group: root
        mode: '0644'

    - name: Flash uboot to Image that will be burned this is to overwrite mobians uboot origin
      command: dd if=/build/crust-meta/build/pinephone/u-boot-sunxi-with-spl.bin of=/build/recovery-pinephone-loop0 seek=8 bs=1024 conv=sync

    - name: Copy file with owner and permissions
      copy:
        src: /build/linux-megi-kernel-5.8/arch/arm64/boot/Image
        dest: /media/root/boot/Image
        owner: root
        group: root
        mode: '0644'

    - name: create ram disk and boot script
      command: /build/scripts/createBootImage.sh
      args:
        chdir: /build/linux-megi-kernel-5.8
